image: python:3.10

before_script:
  - pip install --upgrade pip
  - pip install poetry==1.5.1
  - poetry config virtualenvs.create false --local
  - poetry install --no-ansi

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - echo ** pylint started! **
    - pylint $(git ls-files '*.py')
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual

django_test:
  stage: test
  script:
    - echo Testing Django application
    - cd mega_shop && python manage.py test
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual